[build-sfnt2woff-zopflitem]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "sfnt2woff-zopfli"
version = "0.0.0"
description = "Dummy sfnt2woff-zopfli package for PyPI"
authors = [{name="Your Name", email="you@example.com"}]
readme = "README.md"
requires-python = ">=3.7"

[tool.setuptools.packages.find]
where = ["src"]
